export enum LOCATIONS_CITY {
  BENGALURU = "Bengaluru",
  MYSORE = "Mysore",
  MUMBAI = "Mumbai",
  CHENNAI = "Chennai",
  DELHI = "Delhi",
  NOIDA = "Noida",
  GHAZIABAD = "Gaziabad",
  TUMKUR = "Tumkur",
  KOLKATA = "Kolkata",
  HYDERABAD = "Hyderabad",
  PUNE = "Pune",
  AHMEDABAD = "Ahmedabad",
  CHANDIGARH = "Chandigarh",
  JAIPUR = "Jaipur",
  COIMBATORE = "Coimbatore",
  KOCHI = "Kochi",
  VISAKHAPATNAM = "Visakhapatnam",
  LUCKNOW = "Lucknow",
  INDORE = "Indore",
}

export enum LOCATIONS_STATE {
  KARNATAKA = "Karnataka",
  DELHI = "Delhi",
  UTTAR_PRADESH = "Uttar Pradesh",
  MAHARASHTRA = "Maharashtra",
  TAMIL_NADU = "Tamil Nadu",
  TELANGANA = "Telangana",
}
