export enum LOCATIONS_CITY {
  BENGALURU = "Bengaluru",
  MYSORE = "Mysore",
  MUMBAI = "Mumbai",
  CHENNAI = "Chennai",
  DELHI = "Delhi",
  NOIDA = "Noida",
  GHAZIABAD = "Gaziabad",
  TUMKUR = "Tumkur",
  KOLKATA = "Kolkata",
  HYDERABAD = "Hyderabad",
  PUNE = "Pune",
  AHMEDABAD = "Ahmedabad",
  CHANDIGARH = "Chandigarh",
  JAIPUR = "Jaipur",
  COIMBATORE = "Coimbatore",
  KOCHI = "Kochi",
  VISAKHAPATNAM = "Visakhapatnam",
  LUCKNOW = "Lucknow",
  INDORE = "Indore",
  KOLAR = "Kolar",
  GURGAON = "Gurgaon",
  FARIDABAD = "Faridabad",
  PANCHKULA = "Panchkula",
  MOHALI = "Mohali",
  MANGALORE = "Mangalore",
}

export enum LOCATIONS_STATE {
  KARNATAKA = "Karnataka",
  DELHI = "Delhi",
  UTTAR_PRADESH = "Uttar Pradesh",
  MAHARASHTRA = "Maharashtra",
  TAMIL_NADU = "Tamil Nadu",
  TELANGANA = "Telangana",
  HARYANA = "Haryana",
  WEST_BENGAL = "West Bengal",
  PUNJAB = "Punjab",
  CHANDIGARH = "Chandigarh",
  RAJASTHAN = "Rajasthan",
}
