const NON_DEAD_MOBILE_PRICE = 500;
const DEAD_MOBILE_PRICE = 200;

const NON_DEAD_LAPTOP_PRICE = 1000;
const DEAD_LAPTOP_PRICE = 300;

export {
  NON_DEAD_LAPTOP_PRICE,
  DEAD_LAPTOP_PRICE,
  NON_DEAD_MOBILE_PRICE,
  DEAD_MOBILE_PRICE,
};
